# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  common-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.23.x"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          sudo apt-get install moreutils -y
          make test
        env:
          CGO_ENABLED: 0

      - name: Checks
        run: make checks

      #    - name: Send coverage
      #      env:
      #        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      #      run: go run github.com/mattn/goveralls@latest -coverprofile=./coverage/covprofile -service=github

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.go-version }}
          path: ./coverage/coverage.html

  ci-124:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.24.x"

      - name: Test
        run: make short-test
        env:
          CGO_ENABLED: 0
